### ISSUE TITLE
Code - ConcurrentModificationException

### ISSUE THREAD

**Issue by leorohr** [leorohr/simulus#17]
After about a minute of running the simulation this exception starts popping up. After it occurs the first time, the frequency of occurrence increases drastically. 
Why? Am I missing a synchronisation somewhere?

Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:886)
    at java.util.ArrayList$Itr.next(ArrayList.java:836)
    at com.simulus.MainApp.redrawCars(MainApp.java:190)
    at com.simulus.controller.SimulationController.lambda$1(SimulationController.java:68)
    at com.simulus.controller.SimulationController$$Lambda$2/1337613873.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:301)
    at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:298)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl$6.run(PlatformImpl.java:298)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by jerrylwang** [comment]
I suspect that the error occurs when two cars overlays each other at an intersection, that you are calling the method lambda to redraw cars and it might cause two objects cars accessing the same tile info and update them at the same time. Now I suspect this error will occur often on a low computational device.   Also, the app crashes after it has been running for 20 mins with NullPointerException. I suspect somewhere in the arrayList we have reached the limit. 

Can you wrap a  Throwable.getCause() method to the lambda redrawCars to see when cause?

**Comment by jerrylwang** [comment]
http://docs.oracle.com/javase/7/docs/api/java/util/ConcurrentModificationException.html

![screen shot 2015-02-07 at 22 25 09](https://cloud.githubusercontent.com/assets/10710831/6094213/6087506a-af18-11e4-9a9e-78d5cbce0116.png)

**Comment by EbrahimMalek** [comment]
It seems that ConcurrentModificationException is thrown when multiple threads try to access the same Array list. We had a similar problem in the updateMap() method in the model class. The problem was overcome by using an iterator to traverse the ArrayList instead of a for loop and .Get(i). We'll look into making similar changes to redrawCars(). Good find.
